baseurl = "http://ranalytics.vn/"
relativeurls = true
title = "Ranalytics.vn - Từ phân tích đến quyết định"
theme = "hugo-universal-theme"
languageCode = "en-us"

# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = "ranalytics-vn"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-117458816-1"


#############################
#MENU OF WEBSITE
#defaultContentLanguageInSubdir = true
#enableRobotsTXT = true

[menu]

# Main menu


[[menu.main]]
    name = "Trang chủ"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "Khóa học"
    identifier = "courses"
    url  = "/courses/"
    weight = 2

[[menu.main]]
    Name = "Tài liệu"
    identifier = "material"
    URL = "#"
    Weight = 3.0
    
#[[menu.main]]
#    enable = false
#    name = "Giới thiệu cơ bản về R"
#    parent = "material"
#    url  = "/lecture/lecture_1.html"
#    weight = 1

#[[menu.main]]
#    name = "Import dữ liệu vào R"
#    parent = "material"
#    url  = "/lecture/lecture_2.html"
#    weight = 2

[[menu.main]]
    name = "R cheatsheets"
    parent = "material"
    url  = "/cheatsheet/"
    weight = 1
    
[[menu.main]]
    name = "Các loại biểu đồ"
    parent = "material"
    url  = "/charts/"
    weight = 2

[[menu.main]]
    name = "FAQ"
    identifier = "faq"
    url  = "/faq/"
    weight = 4
    
[[menu.main]]
    name = "Blog"
    url  = "/blog/"
    weight = 5

[[menu.main]]
    name = "Liên hệ"
    url  = "/contact/"
    weight = 6

# Top bar social links menu

#[[menu.topbar]]
#    weight = 1
#    name = "GitHub"
#    url = "https://github.com/devcows/hugo-universal-theme"
#    pre = "<i class='fa fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 4
    name = "Facebook"
    url = "https://www.facebook.com/groups/ranalytics"
    pre = "<i class='fa fa-2x fa-facebook'></i>"

#[[menu.topbar]]
#    weight = 3
#    name = "Twitter"
#    url = "http://twitter.com"
#    pre = "<i class='fa fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 3
    name = "Email"
    url = "mailto:hoangducanh89@gmail.com"
    pre = "<i class='fa fa-2x fa-envelope'></i>"

[[menu.topbar]]
    weight = 2
    name = "Phone"
    url = "tel:+84977738939"
    pre = "<i class='fa fa-2x fa-phone'></i>"


[params]
    viewMorePostLink = "/blog/"
    author = "DevCows"
    defaultKeywords = ["devows", "hugo", "go"]
    defaultDescription = "Site template made by devcows using hugo"

    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "blue"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "hoangducanh89@gmail.com"

    about_us = "<p>Với RAnalytics.vn, bạn sẽ vững bước hơn trên sự nghiệp phân tích dữ liệu.</p>"
    copyright = "Copyright (c) 2017, Ranalytics.vn - all rights reserved"

    # Format dates with Go's time formatting
    date_format = "2006-01-02"

	math = true

	# Define the number of posts per page
	paginate = 10
	
	highlight = true

	highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml", "markdown"]
#   highlightjsTheme = "railscasts"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"
	
	
    logo = "img/logo.png"
    
    address = """<p> 50 Nguyễn Phúc Lai, Ô Chợ Dừa, Đống Đa, Hà Nội
        <br>
      </p>
      """
#    latitude = "105.8214"
#    longitude = "21.01994"



[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Liên hệ với chúng tôi qua +84 977 738 939</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Ý kiến học viên"
    subtitle = "Sau nhiều khóa đào tạo phân tích dữ liệu với R, hãy xem các học viên đánh giá thế nào về chúng tôi."

[params.see_more]
    enable = true
    icon = "fa fa-diamond"
    title = "RAnalytics là tổ chức giảng dạy R được RStudio công nhận tại Việt Nam"
    subtitle = "Hoàng Đức Anh, đồng sáng lập viên RAnalytics.vn là giảng viên phân tích dữ liệu của RStudio"
    link_url = "https://www.rstudio.com/instructors/"
    link_text = "Xem ngay"

[params.clients]
    enable = false
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Tài liệu"
    subtitle = ""

[params.recent_posts]
    enable = false
    title = "Blog"
    subtitle = "Các bài viết gần nhất"

[params.see_more_2]
    enable = true
    icon = "fa fa-info-circle"
    title = "Về chúng tôi"
    subtitle = "RAnalytics là một nhóm những người sử dụng R, nghiện phân tích số liệu, chuyên về phân tích, trực quan hóa số liệu & xây dựng các mô hình dự báo. Chúng tôi cung cấp các khóa học về R với nhiều chủ đề khác nhau cũng như tư vấn và xử lý các vấn đề khác nhau về phân tích dữ liệu và nghiên cứu thị trường. Chúng tôi thích thảo luận và xử lý các vấn đề thực tế trong phân tích kinh doanh. Các thành viên có hơn 10 năm kinh nghiệm trong phân tích kinh doanh, khoa học số liệu, nghiên cứu thị trường và phát triển website, trong nhiều lĩnh vực khác nhau, gồm có ngân hàng, Mobile, thương mại điện tử và công nghệ thông tin. Sứ mệnh của chúng tôi là đưa sức mạnh của R, phần mềm phân tích mạnh nhất hiện nay, đến với Việt Nam"
    link_url = "https://www.datacamp.com/community/open-courses/h%C6%B0%E1%BB%9Bng-d%E1%BA%ABn-c%C6%A1-b%E1%BA%A3n-v%E1%BB%81-r"
    link_text = "Xem ngay"
    
####TEAM SECTION
# Team section
  [params.team]
    enable = true
    # Possibility to center items
    #center = true
    title = "Các thành viên"
#    subtitle = "Lorem ipsum dolor sit amet consectetur."
#    description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut eaque, laboriosam veritatis, quos non quis ad perspiciatis, totam corporis ea, alias ut unde."

    # All team member's pictures are stored under 'static/img/team'.
    # Replace them with your own too.
    # Suggestion: Image size should be at least 360px*360px or the alignment might be affected.

    [[params.team.members]]
      img = "2-phamdinhduc.png"
      name = "Phạm Đình Đức"
      position = "Data Scientist"
      bio = "8 năm kinh nghiệm phân tích số liệu, xây dựng hệ thống Data Warehouse & tự động hóa báo cáo  trong lĩnh vực ngân hàng, bán lẻ & Ecommerce, tốt nghiệp thạc sỹ tại vương quốc Anh"
      social = [
        ["fa-linkedin", "https://www.linkedin.com/in/duc-pham-35910975/"]
      ]
      
      [[params.team.members]]
      img = "1-hoangducanh.jpg"
      name = "Hoàng Đức Anh"
      position = "Business Analytics Professional"
      # For bio markdown and even multiline strings are available.
      bio = "Giảng viên phân tích dữ liệu của RStudio tại Việt Nam, 5 năm kinh nghiệm trong lĩnh vực phân tích số liệu, 3 năm kinh nghiệm trong E-Commerce & Mobile, 2 năm kinh nghiệm phân tích chuyên sâu các vấn đề trong ngân hàng, xây dựng team phân tích nâng cao cho VPBank. Tốt nghiệp thạc sỹ ngành phân tích định lượng trong kinh tế tại Warsaw"
      social = [
        ["fa-twitter", "https://twitter.com/AnhHoangDuc"],
        ["fa-linkedin", "https://www.linkedin.com/in/hoangducanh/"],
        ["fa-globe", "http://anhhoangduc.com/"],
      ]

    [[params.team.members]]
     img = "3-lekhanhduong.png"
      name = "Lê Khánh Dương"
      position = "Senior Developer"
      bio = "6 năm kinh nghiệm lập trình PHP, Java và xây dựng các hệ thống hỗ trợ Ecommerce & phân tích số liệu"
      social = [
        ["fa-linkedin", "https://www.linkedin.com/in/duonglk/"]
      ]