---
title: Viết công thức toán trong rmarkdown
author: Hoàng Đức Anh
date: '2018-07-18'
slug: viet-cong-thuc-toan-trong-rmarkdown
categories:
  - Writing report
tags: ["Rmarkdown"]
summary: "Các công thức và ký hiệu toán học thường dùng trong Rmarkdown"
banner: "img/banners/banner-10.png"
---

Khi làm việc với `rmarkdown` và `RStudio`, ta có thể viết các công thức, ký hiệu toán học một cách rất dễ dàng. Để viết các công thức toán, có hai cách:

- Cách 1: Công thức toán nằm trong dấu `$` `công thức toán` `$`. Khi đó, công thức sẽ hiển thị nằm trên cùng một dòng.

Ví dụ: `$` `y = x^2` `$` sẽ hiển thị kết quả là $y = x^2$

- Cách 2: Công thức toán nằm trong dấu `$$` `công thức toán` `$$` (hai dấu `$`). Khi đó, công thức sẽ hiển thị sẽ nằm ở một dòng độc lập.

Ví dụ: `$$` `y = x^2` `$$` sẽ hiển thị kết quả là 

$y = x^2$ *(xuống dòng)*

Trong bài viết này, `ranalytics` sẽ hướng dẫn các bạn, đặc biệt là các bạn chưa dùng Latax, viết một số ký hiệu toán học thường dùng.

---

### Ký hiệu tiếng Latin

| Ký hiệu	| Cách viết |
----|-------
$\alpha$ | 	`\alpha`
$\beta$ | 	`\beta`
$\gamma$ | 	`\gamma`
$\Gamma$ | 	`\Gamma`
$\pi$ | 	`\pi`
$\Pi$ | 	`\Pi`
$\phi$ | 	`\phi`
$\Phi$ | 	`\Phi`
$\varphi$ | 	`\varphi`
$\theta$ | 	`\theta`

---

### Ký hiệu toán học

Các ký hiệu toán học viết trong `rmarkdown` có hai nguyên tắc chính như sau:

- Các chỉ số chạy/tham số ở dưới sẽ nằm sau dấu `_` (ví dụ $x_2$, $y_j$), các chỉ số ở vị trí ở phía trên sẽ nằm sau dấu `^` (ví dụ $x^2$, $y^n$)
- Các nhóm tham số cùng thuộc một vị trí sẽ nằm trong dấu `{}`. Ví dụ `y_{n+1}` sẽ cho kết quả là $y_{n+1}$.

Các ký hiệu toán học hay dùng nhất xem trong bảng dưới đây.

| Ký hiệu	| Cách viết |
----|-------
$\to$ | 	`\to`
$\infty$ | 	`\infty`
$k_{n+1}$ | 	`k_{n+1}`
$n^2$ | 	`n^2`
$k_n^2$ | 	`k_n^2`
$\frac{n!}{k!(n-k)!}$ | 	`\frac{n!}{k!(n-k)!}`
$\binom{n}{k}$ | 	`\binom{n}{k}`
$\frac{\frac{x}{1}}{x - y}$ | 	`\frac{\frac{x}{1}}{x - y}`
$^3/_7$ | 	`^3/_7`
$\sqrt{k}$ | 	`\sqrt{k}`
$\sqrt[n]{k}$ | 	`\sqrt[n]{k}`
$\sum_{i=1}^{10} t_i$ | 	`\sum_{i=1}^{10} t_i`
$\int_0^\infty \mathrm{e}^{-x}\,\mathrm{d}x$ | 	`\int_0^\infty \mathrm{e}^{-x}\,\mathrm{d}x`
$\sum$ | 	`\sum`
$\prod$ | 	`\prod`

---

Đối với các ký hiệu toán học khác, các bạn có thể tham khảo ở [https://www.latex4technics.com/](https://www.latex4technics.com/). Sau khi xây dựng xong công thức, các bạn chỉ việc copy vào `rmarkdown`

---

Chúc các bạn học và làm việc hiệu quả với [Ranalytics.vn](ranalytics.vn)!

